/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	samplecrdv1 "github.com/tonyshanc/sample-operator-v1/pkg/apis/samplecrd/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCars implements CarInterface
type FakeCars struct {
	Fake *FakeSamplecrdV1
	ns   string
}

var carsResource = schema.GroupVersionResource{Group: "samplecrd", Version: "v1", Resource: "cars"}

var carsKind = schema.GroupVersionKind{Group: "samplecrd", Version: "v1", Kind: "Car"}

// Get takes name of the car, and returns the corresponding car object, and an error if there is any.
func (c *FakeCars) Get(ctx context.Context, name string, options v1.GetOptions) (result *samplecrdv1.Car, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(carsResource, c.ns, name), &samplecrdv1.Car{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Car), err
}

// List takes label and field selectors, and returns the list of Cars that match those selectors.
func (c *FakeCars) List(ctx context.Context, opts v1.ListOptions) (result *samplecrdv1.CarList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(carsResource, carsKind, c.ns, opts), &samplecrdv1.CarList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &samplecrdv1.CarList{ListMeta: obj.(*samplecrdv1.CarList).ListMeta}
	for _, item := range obj.(*samplecrdv1.CarList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cars.
func (c *FakeCars) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(carsResource, c.ns, opts))

}

// Create takes the representation of a car and creates it.  Returns the server's representation of the car, and an error, if there is any.
func (c *FakeCars) Create(ctx context.Context, car *samplecrdv1.Car, opts v1.CreateOptions) (result *samplecrdv1.Car, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(carsResource, c.ns, car), &samplecrdv1.Car{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Car), err
}

// Update takes the representation of a car and updates it. Returns the server's representation of the car, and an error, if there is any.
func (c *FakeCars) Update(ctx context.Context, car *samplecrdv1.Car, opts v1.UpdateOptions) (result *samplecrdv1.Car, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(carsResource, c.ns, car), &samplecrdv1.Car{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Car), err
}

// Delete takes name of the car and deletes it. Returns an error if one occurs.
func (c *FakeCars) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(carsResource, c.ns, name), &samplecrdv1.Car{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCars) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(carsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &samplecrdv1.CarList{})
	return err
}

// Patch applies the patch and returns the patched car.
func (c *FakeCars) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *samplecrdv1.Car, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(carsResource, c.ns, name, pt, data, subresources...), &samplecrdv1.Car{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.Car), err
}
